# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xms1G -Xmx10G -XX:+UseZGC
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

# Mod properties
mod_id=genesis
mod_name=Genesis
mod_license=Apache 2.0
mod_version=1.21.1-0.8.0-port-true-world-lod7
maven_group=shipwrights.genesis
archives_name=genesis

# Minecraft / NeoForge properties
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.233
loader_version_range=[1,)

# Parchment mappings
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

# Dependencies
zps_version=1.21.1-2.4.2
lodestone_version=1.8.2
pehkui_version=3.8.3+1.21-neoforge
curios_version=9.5.1+1.21.1
fusion_version=1.3.3-neoforge-mc1.21.1
architectury_version=13.0.8+neoforge
kotlin_for_forge_version=5.11.0
create_version=6.0.10+mc1.21.1
create_aeronautics_version=1.3.0+mc1.21.1
create_aeronautics_mod_version=1.3.0
sable_version=2.0.3+mc1.21.1
sable_companion_version=1.6.0
registrate_version=MC1.21-1.3.0+67
spark_version=1.10.124-neoforge-1.21.1
jei_version=19.22.1.316
mekanism_version=10.7.14.79
mekanism_generators_version=10.7.14.79
