modLoader = "javafml"
loaderVersion = "[4,)"
license = "Apache 2.0"

[[mods]]
modId = "genesis"
version = "1.21.1-0.8.0"
displayName = "Genesis"
authors = "G_Mungus, Quoissant, Cosmos, Frisk256, Acrogenous, BrickyBoy, Jcm, metafive, GuyApooye, ThePlasticPotato"
description = '''
A space mod for Create Aeronautics.
'''
logoFile = "assets/genesis/icon.png"

[[mixins]]
config = "genesis.mixins.json"

[[dependencies.genesis]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.genesis]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.genesis]]
modId = "sable"
type = "required"
versionRange = "[2.0.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.genesis]]
modId = "simulated"
type = "required"
versionRange = "[1.0.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.genesis]]
modId = "aeronautics"
type = "required"
versionRange = "[1.0.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.genesis]]
modId = "create"
type = "required"
versionRange = "[6.0.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.genesis]]
modId = "pehkui"
type = "required"
versionRange = "[3.8.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.genesis]]
modId = "lodestone"
type = "required"
versionRange = "[1.7.0,)"
ordering = "NONE"
side = "CLIENT"
