<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AssemblyName>Assembly-CSharp</AssemblyName>
    <Nullable>disable</Nullable><LangVersion>latest</LangVersion>
    <NoWarn>CS0649</NoWarn>
  </PropertyGroup>
  <ItemGroup><ProjectReference Include="../core/core.csproj" /></ItemGroup>
</Project>
