package net.mcreator.crustychunks.init;

import net.neoforged.neoforge.registries.DeferredHolder;
import net.minecraft.core.registries.Registries;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.CreativeModeTabs;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.level.ItemLike;
import net.minecraft.world.level.block.Block;
import net.neoforged.neoforge.event.BuildCreativeModeTabContentsEvent;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.fml.common.EventBusSubscriber.Bus;
import net.neoforged.neoforge.registries.DeferredRegister;

@EventBusSubscriber(
   bus = Bus.MOD
)
public class CrustyChunksModTabs {
   public static final DeferredRegister<CreativeModeTab> REGISTRY = DeferredRegister.create(Registries.CREATIVE_MODE_TAB, "crusty_chunks");
   public static final DeferredHolder<CreativeModeTab, CreativeModeTab> CRUSTY_ORES = REGISTRY.register(
      "crusty_ores",
      () -> CreativeModeTab.builder()
            .title(Component.translatable("item_group.crusty_chunks.crusty_ores"))
            .icon(() -> new ItemStack((ItemLike)CrustyChunksModItems.LEAD_INGOT.get()))
            .displayItems((parameters, tabData) -> {
               tabData.accept((ItemLike)CrustyChunksModItems.ZINC_INGOT.get());
               tabData.accept((ItemLike)CrustyChunksModItems.BRASS_INGOT.get());
               tabData.accept((ItemLike)CrustyChunksModItems.STEEL_INGOT.get());
               tabData.accept((ItemLike)CrustyChunksModItems.LEAD_INGOT.get());
               tabData.accept((ItemLike)CrustyChunksModItems.NICKEL_INGOT.get());
               tabData.accept((ItemLike)CrustyChunksModItems.ALUMINUM_INGOT.get());
               tabData.accept((ItemLike)CrustyChunksModItems.URANIUM_DEPLETED_INGOT.get());
               tabData.accept((ItemLike)CrustyChunksModItems.URANIUM_NEURAL_INGOT.get());
               tabData.accept((ItemLike)CrustyChunksModItems.URANIUM_ENRICHED_INGOT.get());
               tabData.accept((ItemLike)CrustyChunksModItems.BERYLLIUM_INGOT.get());
               tabData.accept((ItemLike)CrustyChunksModItems.LITHIUM_INGOT.get());
               tabData.accept((ItemLike)CrustyChunksModItems.ENRICHED_LITHIUM_INGOT.get());
               tabData.accept((ItemLike)CrustyChunksModItems.PLUTONIUM_INGOT.get());
               tabData.accept((ItemLike)CrustyChunksModItems.NIOBIUM_INGOT.get());
               tabData.accept((ItemLike)CrustyChunksModItems.ADVANCED_ALLOY_MIXTURE.get());
               tabData.accept((ItemLike)CrustyChunksModItems.COMPRESSED_ADVANCED_MIXTURE.get());
               tabData.accept((ItemLike)CrustyChunksModItems.ADVANCED_ALLOY_INGOT.get());
               tabData.accept((ItemLike)CrustyChunksModItems.RAW_ZINC.get());
               tabData.accept((ItemLike)CrustyChunksModItems.RAW_LEAD.get());
               tabData.accept((ItemLike)CrustyChunksModItems.RAW_NICKEL.get());
               tabData.accept((ItemLike)CrustyChunksModItems.RAW_URANIUM.get());
               tabData.accept((ItemLike)CrustyChunksModItems.RAW_BERYLLIUM.get());
               tabData.accept((ItemLike)CrustyChunksModItems.RAW_LITHIUM.get());
               tabData.accept((ItemLike)CrustyChunksModItems.SULFUR.get());
               tabData.accept((ItemLike)CrustyChunksModItems.NITRATE.get());
               tabData.accept((ItemLike)CrustyChunksModItems.PHOSPHORUS_DUST.get());
               tabData.accept((ItemLike)CrustyChunksModItems.TRINITITE_SHARD.get());
               tabData.accept((ItemLike)CrustyChunksModItems.PYROCHLORE.get());
               tabData.accept((ItemLike)CrustyChunksModItems.CHLORINE_DUST.get());
               tabData.accept((ItemLike)CrustyChunksModItems.IRON_DUST.get());
               tabData.accept((ItemLike)CrustyChunksModItems.GOLD_DUST.get());
               tabData.accept((ItemLike)CrustyChunksModItems.COPPER_DUST.get());
               tabData.accept((ItemLike)CrustyChunksModItems.ZINC_DUST.get());
               tabData.accept((ItemLike)CrustyChunksModItems.BRASS_DUST.get());
               tabData.accept((ItemLike)CrustyChunksModItems.LEAD_DUST.get());
               tabData.accept((ItemLike)CrustyChunksModItems.NICKEL_DUST.get());
               tabData.accept((ItemLike)CrustyChunksModItems.BAUXITE_DUST.get());
               tabData.accept((ItemLike)CrustyChunksModItems.ALUMINATE_DUST.get());
               tabData.accept((ItemLike)CrustyChunksModItems.FILTERED_ALUMINATE_DUST.get());
               tabData.accept((ItemLike)CrustyChunksModItems.ALUMINUM_DUST.get());
               tabData.accept((ItemLike)CrustyChunksModItems.ALUMINUM_TINY_DUST.get());
               tabData.accept((ItemLike)CrustyChunksModItems.PYROCHLORE_DUST.get());
               tabData.accept((ItemLike)CrustyChunksModItems.FILTERED_PYROCHLORE_DUST.get());
               tabData.accept((ItemLike)CrustyChunksModItems.NIOBIUM_DUST.get());
               tabData.accept((ItemLike)CrustyChunksModItems.NIOBIUM_TINY_DUST.get());
               tabData.accept((ItemLike)CrustyChunksModItems.URANIUM_NEUTRAL_DUST.get());
               tabData.accept((ItemLike)CrustyChunksModItems.URANIUM_NEUTRALTINY_DUST.get());
               tabData.accept((ItemLike)CrustyChunksModItems.URANIUM_ENRICHED_DUST.get());
               tabData.accept((ItemLike)CrustyChunksModItems.URANIUM_ENRICHED_TINY_DUST.get());
               tabData.accept((ItemLike)CrustyChunksModItems.URANIUM_DEPLETED_DUST.get());
               tabData.accept((ItemLike)CrustyChunksModItems.URANIUM_DEPLETED_TINY_DUST.get());
               tabData.accept((ItemLike)CrustyChunksModItems.BERYLLIUM_DUST.get());
               tabData.accept((ItemLike)CrustyChunksModItems.LITHIUM_DUST.get());
               tabData.accept((ItemLike)CrustyChunksModItems.LITHIUM_DEUTERIDE.get());
               tabData.accept((ItemLike)CrustyChunksModItems.TINY_LITHIUM_DEUTERIDE.get());
               tabData.accept((ItemLike)CrustyChunksModItems.LEAD_NUGGET.get());
               tabData.accept((ItemLike)CrustyChunksModItems.LITHIUM_NUGGET.get());
               tabData.accept((ItemLike)CrustyChunksModItems.ENRICHED_LITHIUM_NUGGET.get());
               tabData.accept((ItemLike)CrustyChunksModItems.PLUTONIUM_NUGGET.get());
               tabData.accept(((Block)CrustyChunksModBlocks.ZINC_BLOCK.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.BRASS_BLOCK.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.STEEL_BLOCK.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.LEAD_BLOCK.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.NICKEL_BLOCK.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_BLOCK.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.URANIUM_DEPLETED_BLOCK.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.URANIUM_NEUTRAL_BLOCK.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.URANIUM_ENRICHED_BLOCK.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.BERYLLIUM_BLOCK.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.LITHIUM_BLOCK.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.PLUTONIUM_BLOCK.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.NIOBIUM_BLOCK.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ADVANCED_ALLOY_BLOCK.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.SULFUR_BLOCK.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.NITRATE_BLOCK.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.PHOSPHATE_BLOCK.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.TRINITITE.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.PYROCHLORE_BLOCK.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.RAW_ZINC_BLOCK.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.RAW_LEAD_BLOCK.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.RAW_NICKEL_BLOCK.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.RAW_URANIUM_BLOCK.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.RAW_BERYLLIUM_BLOCK.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.RAW_LITHIUM_BLOCK.get()).asItem());
               tabData.accept((ItemLike)CrustyChunksModItems.SHALE_OIL.get());
               tabData.accept((ItemLike)CrustyChunksModItems.CRUDE_OIL_BUCKET.get());
               tabData.accept((ItemLike)CrustyChunksModItems.OIL_BUCKET.get());
               tabData.accept((ItemLike)CrustyChunksModItems.DIESEL_BUCKET.get());
               tabData.accept((ItemLike)CrustyChunksModItems.KEROSENE_BUCKET.get());
               tabData.accept((ItemLike)CrustyChunksModItems.PETROLIUM_BUCKET.get());
               tabData.accept(((Block)CrustyChunksModBlocks.TAR.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ZINC_ORE.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.LEAD_ORE.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.DEEPSLATE_LEAD_ORE.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.NICKEL_ORE.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.SULFUR_ORE.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.URANIUM_ORE.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.BERYLLIUM_ORE.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.LITHIUM_ORE.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.PYROCHLORE_ORE.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.BAUXITE.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.RADIOACTIVE_ASH_FULL_BLOCK.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.RADIOACTIVE_ASH.get()).asItem());
               tabData.accept((ItemLike)CrustyChunksModItems.SULFURIC_ACID_BUCKET.get());
               tabData.accept((ItemLike)CrustyChunksModItems.HYDRAZINE_BUCKET.get());
            })
            .build()
   );
   public static final DeferredHolder<CreativeModeTab, CreativeModeTab> CRUSTY_PRODUCTION = REGISTRY.register(
      "crusty_production",
      () -> CreativeModeTab.builder()
            .title(Component.translatable("item_group.crusty_chunks.crusty_production"))
            .icon(() -> new ItemStack((ItemLike)CrustyChunksModBlocks.ASSEMBLY_CRUSHER.get()))
            .displayItems((parameters, tabData) -> {
               tabData.accept(((Block)CrustyChunksModBlocks.THERMAL_FURNACE.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.BLAST_FURNACE.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.BLAST_FURNACE_BRICKS.get()).asItem());
               tabData.accept((ItemLike)CrustyChunksModItems.BLAST_CLAY.get());
               tabData.accept((ItemLike)CrustyChunksModItems.BLAST_FURNACE_BRICK.get());
               tabData.accept(((Block)CrustyChunksModBlocks.BLAST_FUNNEL.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.FOUNDRY.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.FIREBOX.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ELECTRIC_FIREBOX.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.OIL_FIREBOX.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.REFINERY.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.REFINERY_TOWER.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.MINERAL_GRINDER.get()).asItem());
               tabData.accept((ItemLike)CrustyChunksModItems.CHISEL.get());
               tabData.accept((ItemLike)CrustyChunksModItems.HAMMER.get());
               tabData.accept((ItemLike)CrustyChunksModItems.CUTTERS.get());
               tabData.accept((ItemLike)CrustyChunksModItems.FOUNDRY_TEMPLATE.get());
               tabData.accept((ItemLike)CrustyChunksModItems.COMPONENT_FOUNDRY_TEMPLATE.get());
               tabData.accept((ItemLike)CrustyChunksModItems.CYLINDER_FOUNDRY_TEMPLATE.get());
               tabData.accept((ItemLike)CrustyChunksModItems.SMALL_PROJECTILE_FOUNDRY_TEMPLATE.get());
               tabData.accept((ItemLike)CrustyChunksModItems.MEDIUM_PROJECTILE_FOUNDRY_TEMPLATE.get());
               tabData.accept((ItemLike)CrustyChunksModItems.LARGE_PROJECTILE_FOUNDRY_TEMPLATE.get());
               tabData.accept((ItemLike)CrustyChunksModItems.EXTRA_LARGE_PROJECTILE_TEMPLATE.get());
               tabData.accept((ItemLike)CrustyChunksModItems.HUGE_PROJECTILE_FOUNDRY_TEMPLATE.get());
               tabData.accept((ItemLike)CrustyChunksModItems.LARGE_FOUNDRY_TEMPLATE.get());
               tabData.accept((ItemLike)CrustyChunksModItems.SMALL_BARREL_TEMPLATE.get());
               tabData.accept((ItemLike)CrustyChunksModItems.MEDIUM_BARREL_TEMPLATE.get());
               tabData.accept((ItemLike)CrustyChunksModItems.LARGE_BARREL_TEMPLATE.get());
               tabData.accept((ItemLike)CrustyChunksModItems.HUGE_BARREL_FOUNDRY_TEMPLATE.get());
               tabData.accept((ItemLike)CrustyChunksModItems.SMALL_CANNON_FOUNDRY_TEMPLATE.get());
               tabData.accept((ItemLike)CrustyChunksModItems.MEDIUM_CANNON_FOUNDRY_TEMPLATE.get());
               tabData.accept((ItemLike)CrustyChunksModItems.LARGE_CANNON_FOUNDRY_TEMPLATE.get());
               tabData.accept((ItemLike)CrustyChunksModItems.HUGE_CANNON_FOUNDRY_TEMPLATE.get());
               tabData.accept(((Block)CrustyChunksModBlocks.GIANT_COIL.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.REACTION_CHAMBER.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.BREEDER_REACTOR_PORT.get()).asItem());
               tabData.accept((ItemLike)CrustyChunksModItems.HAND_DRILL.get());
               tabData.accept(((Block)CrustyChunksModBlocks.BREEDER_REACTOR_CORE.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.BREEDER_REACTOR_INTERFACE.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.REACTOR_CASING.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.CONTROL_ROD.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.EMPTY_FUEL_RODS.get()).asItem());
               tabData.accept((ItemLike)CrustyChunksModItems.FUEL_ROD.get());
               tabData.accept(((Block)CrustyChunksModBlocks.POWER_REACTOR_INTERFACE.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.POWER_REACTOR_PORT.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.PRODUCTION_INPUT.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.PRODUCTION_OUTPUT.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ASSEMBLY_DEPOT.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ASSEMBLY_MACHINE.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ASSEMBLY_CRUSHER.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ASSEMBLY_FURNACE.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ASSEMBLY_CIRCUIT_FABRICATOR.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ASSEMBLY_MECHANICAL_FABRICATOR.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.BAUXITE_DIGESTER.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ASSEMBLY_CENTRIFUGE_MIDDLE.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ASSEMBLY_CENTRIFUGE_TOP.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ASSEMBLY_CENTRIFUGE_BOTTOM.get()).asItem());
               tabData.accept((ItemLike)CrustyChunksModItems.MECHANICAL_BORE.get());
               tabData.accept((ItemLike)CrustyChunksModItems.MECHANICAL_PRESS.get());
               tabData.accept((ItemLike)CrustyChunksModItems.MECHANICAL_EXTRUDER.get());
               tabData.accept((ItemLike)CrustyChunksModItems.MECHANICAL_SHEAR.get());
               tabData.accept((ItemLike)CrustyChunksModItems.IRONGEAR.get());
               tabData.accept((ItemLike)CrustyChunksModItems.STEEL_CRUSHING_WHEEL.get());
               tabData.accept((ItemLike)CrustyChunksModItems.WELDER.get());
            })
            .withTabsBefore(new ResourceLocation[]{CRUSTY_ORES.getId()})
            .build()
   );
   public static final DeferredHolder<CreativeModeTab, CreativeModeTab> WARIUM_LOGISTICS = REGISTRY.register(
      "warium_logistics",
      () -> CreativeModeTab.builder()
            .title(Component.translatable("item_group.crusty_chunks.warium_logistics"))
            .icon(() -> new ItemStack((ItemLike)CrustyChunksModBlocks.CONVEYOR.get()))
            .displayItems((parameters, tabData) -> {
               tabData.accept(((Block)CrustyChunksModBlocks.CONVEYOR.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.CONVEYOR_SPLITTER.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.GENERATOR.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ENERGY_NODE.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ENERGY_BATTERY.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.LARGE_ELECTRIC_MOTOR.get()).asItem());
               tabData.accept((ItemLike)CrustyChunksModItems.CABLE.get());
               tabData.accept((ItemLike)CrustyChunksModItems.ENERGY_METER.get());
               tabData.accept(((Block)CrustyChunksModBlocks.JET_COMPRESSOR.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.JET_TURBINE.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.JET_EXHAUST.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.AFTER_BURNER.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.JET_GEARBOX.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.PASSENGER_SEAT.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.FUEL_TANK.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.FUEL_TANK_MODULE.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.FUEL_TANK_INPUT.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.LARGE_ENGINE_SMOKESTACK.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ENGINE_CYLLINDER.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.DRIVE_SHAFT.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.EXTENSION_SHAFT.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.REDIRECTOR_SHAFT.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ENERGY_DISTRIBUTION_NODE.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.MANUAL_CRANK.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.SOLAR_GENERATOR.get()).asItem());
               tabData.accept((ItemLike)CrustyChunksModItems.FUEL_HOSE.get());
               tabData.accept(((Block)CrustyChunksModBlocks.SMALL_PETROL_ENGINE.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.MEDIUM_PETROL_ENGINE.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.SMALL_DIESEL_ENGINE.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.MEDIUM_DIESEL_ENGINE.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.LIGHT_TURBINE_ENGINE.get()).asItem());
               tabData.accept((ItemLike)CrustyChunksModItems.THERMOMETER.get());
               tabData.accept((ItemLike)CrustyChunksModItems.GAS_CANISTER.get());
               tabData.accept(((Block)CrustyChunksModBlocks.ITEM_INCINERATOR.get()).asItem());
            })
            .withTabsBefore(new ResourceLocation[]{CRUSTY_PRODUCTION.getId()})
            .build()
   );
   public static final DeferredHolder<CreativeModeTab, CreativeModeTab> CRUSTY_COMPONENTS = REGISTRY.register(
      "crusty_components",
      () -> CreativeModeTab.builder()
            .title(Component.translatable("item_group.crusty_chunks.crusty_components"))
            .icon(() -> new ItemStack((ItemLike)CrustyChunksModItems.ADVANCED_COMPONENT.get()))
            .displayItems((parameters, tabData) -> {
               tabData.accept((ItemLike)CrustyChunksModItems.WOOD_COMPONENT.get());
               tabData.accept((ItemLike)CrustyChunksModItems.IRON_TUBE.get());
               tabData.accept((ItemLike)CrustyChunksModItems.STEELPLATE.get());
               tabData.accept((ItemLike)CrustyChunksModItems.ALUMINUM_PLATE.get());
               tabData.accept((ItemLike)CrustyChunksModItems.BRASS_PLATE.get());
               tabData.accept((ItemLike)CrustyChunksModItems.COPPER_PLATE.get());
               tabData.accept((ItemLike)CrustyChunksModItems.BENT_COMPONENT.get());
               tabData.accept((ItemLike)CrustyChunksModItems.STEEL_GEAR.get());
               tabData.accept((ItemLike)CrustyChunksModItems.STEEL_COMPONENT.get());
               tabData.accept((ItemLike)CrustyChunksModItems.ADVANCED_COMPONENT.get());
               tabData.accept((ItemLike)CrustyChunksModItems.PRECISION_COMPONENT.get());
               tabData.accept((ItemLike)CrustyChunksModItems.ADVANCED_ALLOY_COMPONENT.get());
               tabData.accept((ItemLike)CrustyChunksModItems.CAST_COMPONENT.get());
               tabData.accept((ItemLike)CrustyChunksModItems.STEEL_CYLINDER.get());
               tabData.accept((ItemLike)CrustyChunksModItems.STEEL_SPRING.get());
               tabData.accept((ItemLike)CrustyChunksModItems.STEEL_TUBE.get());
               tabData.accept((ItemLike)CrustyChunksModItems.STEEL_WIRE.get());
               tabData.accept((ItemLike)CrustyChunksModItems.CUT_COMPONENT.get());
               tabData.accept((ItemLike)CrustyChunksModItems.BORED_COMPONENT.get());
               tabData.accept((ItemLike)CrustyChunksModItems.COPPER_COIL.get());
               tabData.accept((ItemLike)CrustyChunksModItems.COPPER_WIRE.get());
               tabData.accept((ItemLike)CrustyChunksModItems.COMBUSTION_CYLINDER.get());
               tabData.accept((ItemLike)CrustyChunksModItems.ELECTRIC_MOTOR.get());
               tabData.accept((ItemLike)CrustyChunksModItems.ENGINE_COMPONENT.get());
               tabData.accept((ItemLike)CrustyChunksModItems.SMALL_ENGINE.get());
               tabData.accept((ItemLike)CrustyChunksModItems.UNFABRICATED_TECH_COMPONENT.get());
               tabData.accept((ItemLike)CrustyChunksModItems.TECH_COMPONENT.get());
               tabData.accept((ItemLike)CrustyChunksModItems.RADAR_COMPONENT.get());
               tabData.accept((ItemLike)CrustyChunksModItems.IR_COMPONENT.get());
               tabData.accept((ItemLike)CrustyChunksModItems.PROPELLENT.get());
               tabData.accept((ItemLike)CrustyChunksModItems.VOLATILE_DUST.get());
               tabData.accept((ItemLike)CrustyChunksModItems.LARGE_VOLATILE_PILE.get());
               tabData.accept((ItemLike)CrustyChunksModItems.SMOKE_AGENT.get());
               tabData.accept((ItemLike)CrustyChunksModItems.FIRE_AGENT.get());
               tabData.accept((ItemLike)CrustyChunksModItems.TOXIC_AGENT.get());
               tabData.accept((ItemLike)CrustyChunksModItems.IMPACT_FUZE.get());
               tabData.accept((ItemLike)CrustyChunksModItems.TIMED_FUZE.get());
               tabData.accept((ItemLike)CrustyChunksModItems.SHAPED_CHARGE_FUZE.get());
               tabData.accept((ItemLike)CrustyChunksModItems.IMPLOSION_MODULE.get());
               tabData.accept((ItemLike)CrustyChunksModItems.NEUTRON_REFLECTOR.get());
               tabData.accept((ItemLike)CrustyChunksModItems.SHIELDING_COMPONENT.get());
               tabData.accept((ItemLike)CrustyChunksModItems.PLUTONIUM_CORE.get());
               tabData.accept((ItemLike)CrustyChunksModItems.THERMO_NUCLEAR_FUEL.get());
               tabData.accept((ItemLike)CrustyChunksModItems.BRASS_FITTING.get());
               tabData.accept((ItemLike)CrustyChunksModItems.TURBINE_ROTOR.get());
               tabData.accept((ItemLike)CrustyChunksModItems.POWER_CELL.get());
               tabData.accept((ItemLike)CrustyChunksModItems.PAINT_TOOL.get());
               tabData.accept((ItemLike)CrustyChunksModItems.RIFLE_STOCK.get());
               tabData.accept((ItemLike)CrustyChunksModItems.SMALL_CASING.get());
               tabData.accept((ItemLike)CrustyChunksModItems.MEDIUM_CASING.get());
               tabData.accept((ItemLike)CrustyChunksModItems.LARGE_CASING.get());
               tabData.accept((ItemLike)CrustyChunksModItems.EXTRA_LARGE_CASING.get());
               tabData.accept((ItemLike)CrustyChunksModItems.HUGE_CASING.get());
               tabData.accept((ItemLike)CrustyChunksModItems.SHOTGUN_CASING.get());
               tabData.accept((ItemLike)CrustyChunksModItems.SMALL_PROJECTILE.get());
               tabData.accept((ItemLike)CrustyChunksModItems.MEDIUM_PROJECTILE.get());
               tabData.accept((ItemLike)CrustyChunksModItems.LARGE_PROJECTILE.get());
               tabData.accept((ItemLike)CrustyChunksModItems.EXTRA_LARGE_PROJECTILE.get());
               tabData.accept((ItemLike)CrustyChunksModItems.HUGE_PROJECTILE.get());
               tabData.accept((ItemLike)CrustyChunksModItems.HOLLOWED_LARGE_PROJECTILE.get());
               tabData.accept((ItemLike)CrustyChunksModItems.HOLLOWED_EXTRA_LARGE_PROJECTILE.get());
               tabData.accept((ItemLike)CrustyChunksModItems.HOLLOWED_HUGE_PROJECTILE.get());
               tabData.accept((ItemLike)CrustyChunksModItems.SMALL_UNBORED_BARREL.get());
               tabData.accept((ItemLike)CrustyChunksModItems.MEDIUM_UNBORED_BARREL.get());
               tabData.accept((ItemLike)CrustyChunksModItems.LARGE_UNBORED_BARREL.get());
               tabData.accept((ItemLike)CrustyChunksModItems.HUGE_UNBORED_BARREL.get());
               tabData.accept((ItemLike)CrustyChunksModItems.SMALL_UNBORED_CANNON_BARREL.get());
               tabData.accept((ItemLike)CrustyChunksModItems.MEDIUM_UNBORED_CANNON_BARREL.get());
               tabData.accept((ItemLike)CrustyChunksModItems.LARGE_UNBORED_CANNON_BARREL.get());
               tabData.accept((ItemLike)CrustyChunksModItems.HUGE_UNBORED_CANNON_BARREL.get());
               tabData.accept((ItemLike)CrustyChunksModItems.SMALL_BORED_BARREL.get());
               tabData.accept((ItemLike)CrustyChunksModItems.MEDIUM_BORED_BARREL.get());
               tabData.accept((ItemLike)CrustyChunksModItems.LARGE_BORED_BARREL.get());
               tabData.accept((ItemLike)CrustyChunksModItems.HUGE_BORED_BARREL.get());
               tabData.accept((ItemLike)CrustyChunksModItems.WEAPON_SUPRESSOR.get());
               tabData.accept((ItemLike)CrustyChunksModItems.SOLID_ROCKET_FUEL_PACK.get());
               tabData.accept((ItemLike)CrustyChunksModItems.FIRING_PIN.get());
               tabData.accept((ItemLike)CrustyChunksModItems.WEAPON_BOLT.get());
               tabData.accept((ItemLike)CrustyChunksModItems.FIRING_MECHANISM.get());
               tabData.accept((ItemLike)CrustyChunksModItems.PISTOL_RECEIVER.get());
               tabData.accept((ItemLike)CrustyChunksModItems.REVOLVER_RECEIVER.get());
               tabData.accept((ItemLike)CrustyChunksModItems.ADVANCED_PISTOL_RECEIVER.get());
               tabData.accept((ItemLike)CrustyChunksModItems.BASIC_RECEIVER.get());
               tabData.accept((ItemLike)CrustyChunksModItems.BOLT_ACTION_RECEIVER.get());
               tabData.accept((ItemLike)CrustyChunksModItems.AUTOMATIC_RIFLE_RECEIVER.get());
               tabData.accept((ItemLike)CrustyChunksModItems.ADVANCED_AUTOMATIC_RIFLE_RECEIVER.get());
               tabData.accept((ItemLike)CrustyChunksModItems.SMG_RECEIVER.get());
               tabData.accept((ItemLike)CrustyChunksModItems.MG_RECEIVER.get());
               tabData.accept((ItemLike)CrustyChunksModItems.SMALL_HE_PROJECTILE.get());
               tabData.accept((ItemLike)CrustyChunksModItems.SMALL_FLAK_PROJECTILE.get());
               tabData.accept((ItemLike)CrustyChunksModItems.HE_PROJECTILE.get());
               tabData.accept((ItemLike)CrustyChunksModItems.FLAK_PROJECTILE.get());
               tabData.accept((ItemLike)CrustyChunksModItems.HEAT_PROJECTILE.get());
               tabData.accept((ItemLike)CrustyChunksModItems.APFSDS_PROJECTILE.get());
               tabData.accept((ItemLike)CrustyChunksModItems.SMOKE_PROJECTILE.get());
               tabData.accept((ItemLike)CrustyChunksModItems.CANISTER_PROJECTILE.get());
            })
            .withTabsBefore(new ResourceLocation[]{WARIUM_LOGISTICS.getId()})
            .build()
   );
   public static final DeferredHolder<CreativeModeTab, CreativeModeTab> CRUSTY_BUILDING = REGISTRY.register(
      "crusty_building",
      () -> CreativeModeTab.builder()
            .title(Component.translatable("item_group.crusty_chunks.crusty_building"))
            .icon(() -> new ItemStack((ItemLike)CrustyChunksModBlocks.SHEET_METAL.get()))
            .displayItems((parameters, tabData) -> {
               tabData.accept(((Block)CrustyChunksModBlocks.REENFORCED_CONCRETE.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.RAZOR_WIRE.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.WIRE_FENCE.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.CONCRETE_WALL.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.SHEET_METAL.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.SHEET_METAL_PANE.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.REBAR.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ASPHALT.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ASPHALT_SLAB.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.SHEET_METAL_SLAB.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.SHEET_METAL_STAIRS.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.SAND_BAGS.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.STEEL_DOOR.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.OVERGROWN_REENFORCED_CONCRETE.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.RUSTY_BLOCK.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.RUSTY_SLAB.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.RUSTY_STAIRS.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.RUSTY_TRAPDOOR.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.STRUCTURAL_CONCRETE.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.STEEL_TRUSS.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.GLASS_TRAPDOOR.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.REINFORCED_GLASS.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.REINFORCED_GLASS_TRAPDOOR.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.REINFORCED_GLASS_STAIRS.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.POLISHED_TRINITITE.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.TINTED_GLASS_TRAPDOOR.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.TINTED_GLASS_STAIRS.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.SIREN.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ANCIENT_LIGHT.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.TRINITITE_GLASS.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.TRINITITE_GLASS_TRAPDOOR.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.TRINITITE_GLASS_STAIRS.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.POLISHED_BAUXITE.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.LIGHT_WOOD_FRAME.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.LIGHT_WOOD_BLOCK.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.LIGHT_WOOD_SLAB.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.LIGHT_WOOD_STAIRS.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.LIGHT_WOOD_SIDE_PANEL.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.LIGHT_WOOD_TRAPDOOR.get()).asItem());
            })
            .withTabsBefore(new ResourceLocation[]{CRUSTY_COMPONENTS.getId()})
            .build()
   );
   public static final DeferredHolder<CreativeModeTab, CreativeModeTab> WARIUM_AMMUNITION = REGISTRY.register(
      "warium_ammunition",
      () -> CreativeModeTab.builder()
            .title(Component.translatable("item_group.crusty_chunks.warium_ammunition"))
            .icon(() -> new ItemStack((ItemLike)CrustyChunksModItems.ARTILLERY_SHELL.get()))
            .displayItems((parameters, tabData) -> {
               tabData.accept((ItemLike)CrustyChunksModItems.MUSKET_BALL.get());
               tabData.accept((ItemLike)CrustyChunksModItems.SMALLBULLET.get());
               tabData.accept((ItemLike)CrustyChunksModItems.SMALL_HOLLOW_POINT_BULLET.get());
               tabData.accept((ItemLike)CrustyChunksModItems.SMALL_STEALTH_BULLET.get());
               tabData.accept((ItemLike)CrustyChunksModItems.MEDIUM_AP_BULLET.get());
               tabData.accept((ItemLike)CrustyChunksModItems.BULLET.get());
               tabData.accept((ItemLike)CrustyChunksModItems.MEDIUM_STEALTH_BULLET.get());
               tabData.accept((ItemLike)CrustyChunksModItems.AP_LARGE_BULLET.get());
               tabData.accept((ItemLike)CrustyChunksModItems.LARGE_BULLET.get());
               tabData.accept((ItemLike)CrustyChunksModItems.STEALTH_LARGE_BULLET.get());
               tabData.accept((ItemLike)CrustyChunksModItems.SLUG_SHELL.get());
               tabData.accept((ItemLike)CrustyChunksModItems.SHOTGUN_SHELL.get());
               tabData.accept((ItemLike)CrustyChunksModItems.BIRD_SHOT.get());
               tabData.accept((ItemLike)CrustyChunksModItems.THERMAL_SHELL.get());
               tabData.accept((ItemLike)CrustyChunksModItems.EXTRA_LARGE_BULLET.get());
               tabData.accept((ItemLike)CrustyChunksModItems.HUGE_HE_BULLET.get());
               tabData.accept((ItemLike)CrustyChunksModItems.HUGE_BULLET.get());
               tabData.accept((ItemLike)CrustyChunksModItems.SMALL_AP_SHELL.get());
               tabData.accept((ItemLike)CrustyChunksModItems.SMALL_SHELL.get());
               tabData.accept((ItemLike)CrustyChunksModItems.SMALL_FLAK_SHELL.get());
               tabData.accept((ItemLike)CrustyChunksModItems.SOLID_SHELL.get());
               tabData.accept((ItemLike)CrustyChunksModItems.LARGE_SHELL.get());
               tabData.accept((ItemLike)CrustyChunksModItems.HEAT_SHELL.get());
               tabData.accept((ItemLike)CrustyChunksModItems.AP_SHELL.get());
               tabData.accept((ItemLike)CrustyChunksModItems.FLAK_SHELL.get());
               tabData.accept((ItemLike)CrustyChunksModItems.SMOKE_SHELL.get());
               tabData.accept((ItemLike)CrustyChunksModItems.CANISTER_SHELL.get());
               tabData.accept((ItemLike)CrustyChunksModItems.ARTILLERY_SHELL.get());
               tabData.accept((ItemLike)CrustyChunksModItems.GAS_ARTILLERY_SHELL.get());
               tabData.accept((ItemLike)CrustyChunksModItems.FIRE_ARTILLERY_SHELL.get());
               tabData.accept((ItemLike)CrustyChunksModItems.ARTILLERY_SOLID_SHELL.get());
               tabData.accept((ItemLike)CrustyChunksModItems.POWDER_CHARGE.get());
               tabData.accept((ItemLike)CrustyChunksModItems.MORTAR_SHELL.get());
               tabData.accept((ItemLike)CrustyChunksModItems.SMOKE_MORTAR_SHELL.get());
               tabData.accept((ItemLike)CrustyChunksModItems.ARMOR_PEELER_ROCKET.get());
               tabData.accept((ItemLike)CrustyChunksModItems.FIRE_SPEAR_ROCKET.get());
               tabData.accept((ItemLike)CrustyChunksModItems.SEEKER_SPEAR_ROCKET.get());
               tabData.accept((ItemLike)CrustyChunksModItems.RADAR_SPEAR_MISSILE.get());
               tabData.accept((ItemLike)CrustyChunksModItems.STRIKE_SPEAR_MISSILE.get());
               tabData.accept((ItemLike)CrustyChunksModItems.FLARE_CHARGE.get());
               tabData.accept((ItemLike)CrustyChunksModItems.CHAFF_CHARGE.get());
               tabData.accept((ItemLike)CrustyChunksModItems.GRENADE_SHELL.get());
               tabData.accept((ItemLike)CrustyChunksModItems.SMOKE_GRENADE_SHELL.get());
            })
            .withTabsBefore(new ResourceLocation[]{CRUSTY_BUILDING.getId()})
            .build()
   );
   public static final DeferredHolder<CreativeModeTab, CreativeModeTab> CRUSTY_ARSENAL = REGISTRY.register(
      "crusty_arsenal",
      () -> CreativeModeTab.builder()
            .title(Component.translatable("item_group.crusty_chunks.crusty_arsenal"))
            .icon(() -> new ItemStack((ItemLike)CrustyChunksModItems.BULLET_RESISTANT_HELMET_HELMET.get()))
            .displayItems((parameters, tabData) -> {
               tabData.accept((ItemLike)CrustyChunksModItems.GRENADE.get());
               tabData.accept((ItemLike)CrustyChunksModItems.INCENDIARY_GRENADE.get());
               tabData.accept((ItemLike)CrustyChunksModItems.SMOKE_GRENADE.get());
               tabData.accept((ItemLike)CrustyChunksModItems.INCENDIARY_BOTTLE.get());
               tabData.accept((ItemLike)CrustyChunksModItems.SMALLMAGAZINE.get());
               tabData.accept((ItemLike)CrustyChunksModItems.SMG_MAGAZINE.get());
               tabData.accept((ItemLike)CrustyChunksModItems.MEDIUM_MAGAZINE.get());
               tabData.accept((ItemLike)CrustyChunksModItems.LARGE_MAGAZINE.get());
               tabData.accept((ItemLike)CrustyChunksModItems.LMG_MAGAZINE.get());
               tabData.accept((ItemLike)CrustyChunksModItems.MACHINE_GUN_BOX.get());
               tabData.accept(((Block)CrustyChunksModBlocks.AUTOCANNON_DRUM.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.MINIGUN.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.MINI_GUN_BARREL.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.LIGHT_MACHINE_GUN.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.MACHINE_GUN.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.HEAVY_MACHINE_GUN.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.MACHINE_GUN_BARREL.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.COVERED_MACHINE_GUN_BARREL.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.SMOKE_LAUNCHER.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.MORTAR.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.FLAME_THROWER.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.FLAME_THROWER_BARREL.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.COVERED_FLAME_THROWER_BARREL.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ROTARY_AUTO_CANNON.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.RAC_BARREL.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.AUTOCANNON.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.LIGHT_AUTOCANNON.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.AUTOCANNON_BARREL.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.BATTLE_CANNON_BREECH.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.BATTLE_CANNON_MANTLET.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.BATTLE_CANNON_BARREL.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.THICK_BATTLE_CANNON_BARREL.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.TYPE_1_BC_MUZZLE_BRAKE.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.TYPE_2_BC_MUZZLE_BRAKE.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ARTILLERYBREECH.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ARTILLERY_BARREL.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.AUTOLOADER.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ARTILLERY_CHARGE_LOADER.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ARTILLERY_AUTOLOADER.get()).asItem());
               tabData.accept((ItemLike)CrustyChunksModItems.MUSKET.get());
               tabData.accept((ItemLike)CrustyChunksModItems.AUTO_PISTOL.get());
               tabData.accept((ItemLike)CrustyChunksModItems.SEMI_AUTOMATIC_PISTOL_ANIMATED.get());
               tabData.accept((ItemLike)CrustyChunksModItems.STEALTH_PISTOL.get());
               tabData.accept((ItemLike)CrustyChunksModItems.REVOLVER_ANIMATED.get());
               tabData.accept((ItemLike)CrustyChunksModItems.SMG_ANIMATED.get());
               tabData.accept((ItemLike)CrustyChunksModItems.MACHINE_CARBINE.get());
               tabData.accept((ItemLike)CrustyChunksModItems.LEVER_RIFLE.get());
               tabData.accept((ItemLike)CrustyChunksModItems.SEMI_AUTOMATIC_RIFLE_ANIMATED.get());
               tabData.accept((ItemLike)CrustyChunksModItems.AUTOMATIC_RIFLE.get());
               tabData.accept((ItemLike)CrustyChunksModItems.BURST_RIFLE.get());
               tabData.accept((ItemLike)CrustyChunksModItems.LMG_ANIMATED.get());
               tabData.accept((ItemLike)CrustyChunksModItems.BATTLE_RIFLE.get());
               tabData.accept((ItemLike)CrustyChunksModItems.BOLT_ACTION_RIFLE_ANIMATED.get());
               tabData.accept((ItemLike)CrustyChunksModItems.SCOPED_BOLT_ACTION_RIFLE_ANIMATED.get());
               tabData.accept((ItemLike)CrustyChunksModItems.BREAK_ACTION_SHOTGUN_ANIMATED.get());
               tabData.accept((ItemLike)CrustyChunksModItems.PUMP_ACTION_SHOTGUN_ANIMATED.get());
               tabData.accept((ItemLike)CrustyChunksModItems.BREECH_RIFLE.get());
               tabData.accept((ItemLike)CrustyChunksModItems.SCOPED_BREECH_RIFLE.get());
               tabData.accept((ItemLike)CrustyChunksModItems.SINGLE_SHOT_RIFLE.get());
               tabData.accept((ItemLike)CrustyChunksModItems.FLAME_THROWER_ANIMATED.get());
               tabData.accept((ItemLike)CrustyChunksModItems.GRENADE_LAUNCHER.get());
               tabData.accept((ItemLike)CrustyChunksModItems.ARMOR_PEELER_UNLOADED.get());
               tabData.accept(((Block)CrustyChunksModBlocks.ROCKET_POD.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ROCKET_POD_CHAMBER.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.LARGE_ROCKET_POD_CHAMBER.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.LARGE_ROCKET_POD.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.MANUAL_AIMER.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.AIMER_NODE.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.NODE_TRIGGER.get()).asItem());
               tabData.accept((ItemLike)CrustyChunksModItems.AIMER.get());
               tabData.accept((ItemLike)CrustyChunksModItems.BODY_ARMOR_CHESTPLATE.get());
               tabData.accept((ItemLike)CrustyChunksModItems.BULLET_RESISTANT_HELMET_HELMET.get());
               tabData.accept((ItemLike)CrustyChunksModItems.BULLET_RESISTANT_HELMET_2_HELMET.get());
               tabData.accept((ItemLike)CrustyChunksModItems.BULLET_RESISTANT_HELMET_3_HELMET.get());
               tabData.accept((ItemLike)CrustyChunksModItems.BULLET_RESISTANT_HELMET_4_HELMET.get());
               tabData.accept((ItemLike)CrustyChunksModItems.NVD_HELMET_HELMET.get());
               tabData.accept((ItemLike)CrustyChunksModItems.GAS_MASK_HELMET_HELMET.get());
               tabData.accept((ItemLike)CrustyChunksModItems.GAS_MASK_HELMET.get());
               tabData.accept((ItemLike)CrustyChunksModItems.FLAME_THROWER_TANK_CHESTPLATE.get());
               tabData.accept((ItemLike)CrustyChunksModItems.FLARE_PISTOL.get());
               tabData.accept(((Block)CrustyChunksModBlocks.COUNTERMEASURE_DISPENSER.get()).asItem());
               tabData.accept((ItemLike)CrustyChunksModItems.BLAST_ARMOR_HELMET.get());
               tabData.accept((ItemLike)CrustyChunksModItems.BLAST_ARMOR_CHESTPLATE.get());
               tabData.accept((ItemLike)CrustyChunksModItems.BLAST_ARMOR_LEGGINGS.get());
               tabData.accept((ItemLike)CrustyChunksModItems.BLAST_ARMOR_BOOTS.get());
               tabData.accept((ItemLike)CrustyChunksModItems.ERADICATION.get());
               tabData.accept(((Block)CrustyChunksModBlocks.ERA_4.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ERA_2.get()).asItem());
               tabData.accept((ItemLike)CrustyChunksModItems.ERA_TILE.get());
               tabData.accept(((Block)CrustyChunksModBlocks.OFFSET_ERA_4.get()).asItem());
               tabData.accept((ItemLike)CrustyChunksModItems.GEIGER_COUNTER.get());
            })
            .withTabsBefore(new ResourceLocation[]{WARIUM_AMMUNITION.getId()})
            .build()
   );
   public static final DeferredHolder<CreativeModeTab, CreativeModeTab> CRUSTY_EXPLOSIVES = REGISTRY.register(
      "crusty_explosives",
      () -> CreativeModeTab.builder()
            .title(Component.translatable("item_group.crusty_chunks.crusty_explosives"))
            .icon(() -> new ItemStack((ItemLike)CrustyChunksModBlocks.MEDIUM_BOMB.get()))
            .displayItems((parameters, tabData) -> {
               tabData.accept(((Block)CrustyChunksModBlocks.EMPTY_MISSILE_HARDPOINT.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.SMOKE_BOMB.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.EXPLOSIVE_BARREL.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.MINING_CHARGE.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.GAS_BOMB.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.SMALL_BOMB.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.CLUSTER_OF_BOMBS.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.MEDIUM_BOMB.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ORDINANCE_CORE.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ORDINANCE_THRUSTER.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.TORPEDO_THRUSTER.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ORDINANCE_FINS.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ORDINANCE_HEAVY_WARHEAD.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ORDINANCE_INCENDIARY_WARHEAD.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ORDINANCE_INLINE_WARHEAD.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ORDINANCE_KINETIC_HEAD.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ORDINANCE_IR_SEEKER_HEAD.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ORDINANCE_SARH_SEEKER.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ORDINANCE_CLUSTER_WARHEAD.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ORDINANCE_INLINE_FISSION_WARHEAD.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ORDINANCE_INLINE_FUSION_WARHEAD_STAGE_1.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ORDINANCE_INLINE_FUSION_WARHEAD_STAGE_2.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ORDINANCE_FISSION_INITIATOR_HEAD.get()).asItem());
               tabData.accept((ItemLike)CrustyChunksModItems.FISSION_CORE.get());
               tabData.accept((ItemLike)CrustyChunksModItems.IMPLOSION_LENS.get());
               tabData.accept(((Block)CrustyChunksModBlocks.FISSION_BOMB.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.FUSION_BOMB.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.LAND_MINE.get()).asItem());
               tabData.accept((ItemLike)CrustyChunksModItems.FUSION_CORE.get());
               tabData.accept(((Block)CrustyChunksModBlocks.ORDINANCE_RELOCATOR.get()).asItem());
            })
            .withTabsBefore(new ResourceLocation[]{CRUSTY_ARSENAL.getId()})
            .build()
   );
   public static final DeferredHolder<CreativeModeTab, CreativeModeTab> WARIUM_ARMOR = REGISTRY.register(
      "warium_armor",
      () -> CreativeModeTab.builder()
            .title(Component.translatable("item_group.crusty_chunks.warium_armor"))
            .icon(() -> new ItemStack((ItemLike)CrustyChunksModBlocks.STEEL_PLATING.get()))
            .displayItems((parameters, tabData) -> {
               tabData.accept(((Block)CrustyChunksModBlocks.STEEL_PLATING.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.STEEL_PLATING_SLAB.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.STEEL_PLATING_STAIRS.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.STEEL_TRAPDOOR.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.STEEL_OPTIC.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.GREEN_ARMOR.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.GREEN_ARMOR_SLAB.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.GREEN_ARMOR_STAIRS.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.GREEN_ARMOR_TRAPDOOR.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.GREEN_ARMOR_OPTIC.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.YELLOW_ARMOR.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.YELLOW_ARMOR_SLAB.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.YELLOW_ARMOR_STAIRS.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.YELLOW_ARMOR_TRAPDOOR.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.YELLOW_ARMOR_OPTIC.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.BROWN_ARMOR.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.BROWN_ARMOR_SLAB.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.BROWN_ARMOR_STAIRS.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.BROWN_ARMOR_TRAPDOOR.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.BROWN_ARMOR_OPTIC.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.WHITE_ARMOR.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.WHITE_ARMOR_SLAB.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.WHITE_ARMOR_STAIRS.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.WHITE_ARMOR_TRAPDOOR.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.WHITE_ARMOR_OPTIC.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.RED_ARMOR.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.RED_ARMOR_SLAB.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.RED_ARMOR_STAIRS.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.RED_ARMOR_TRAPDOOR.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.RED_ARMOR_OPTIC.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.BLACK_ARMOR.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.BLACK_ARMOR_SLAB.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.BLACK_ARMOR_STAIRS.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.BLACK_ARMOR_TRAPDOOR.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.BLACK_ARMOR_OPTIC.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.CYAN_ARMOR.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.CYAN_ARMOR_SLAB.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.CYAN_ARMOR_STAIRS.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.CYAN_ARMOR_TRAPDOOR.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.CYAN_ARMOR_OPTIC.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.BLUE_ARMOR.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.BLUE_ARMOR_SLAB.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.BLUE_ARMOR_STAIRS.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.BLUE_ARMOR_TRAPDOOR.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.BLUE_ARMOR_OPTIC.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ORANGE_ARMOR.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ORANGE_ARMOR_SLAB.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ORANGE_ARMOR_STAIRS.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ORANGE_ARMOR_TRAPDOOR.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ORANGE_ARMOR_OPTIC.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.GRAY_ARMOR.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.GRAY_ARMOR_SLAB.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.GRAY_ARMOR_STAIRS.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.GRAY_ARMOR_TRAPDOOR.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.GRAY_ARMOR_OPTIC.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.LIME_ARMOR.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.LIME_ARMOR_SLAB.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.LIME_ARMOR_STAIRS.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.LIME_ARMOR_TRAPDOOR.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.LIME_ARMOR_OPTIC.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.LIGHT_GRAY_ARMOR.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.LIGHT_GRAY_ARMOR_SLAB.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.LIGHT_GRAY_ARMOR_STAIRS.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.LIGHT_GRAY_ARMOR_TRAPDOOR.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.LIGHT_GRAY_ARMOR_OPTIC.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.LIGHT_BLUE_ARMOR.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.LIGHT_BLUE_ARMOR_SLAB.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.LIGHT_BLUE_ARMOR_STAIRS.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.LIGHT_BLUE_ARMOR_TRAPDOOR.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.LIGHT_BLUE_ARMOR_OPTIC.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.PINK_ARMOR.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.PINK_ARMOR_SLAB.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.PINK_ARMOR_STAIRS.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.PINK_ARMOR_TRAPDOOR.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.PINK_ARMOR_OPTIC.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.MAGENTA_ARMOR.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.MAGENTA_ARMOR_SLAB.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.MAGENTA_ARMOR_STAIRS.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.MAGENTA_ARMOR_TRAPDOOR.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.MAGENTA_ARMOR_OPTIC.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.PURPLE_ARMOR.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.PURPLE_ARMOR_SLAB.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.PURPLE_ARMOR_STAIRS.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.PURPLE_ARMOR_TRAPDOOR.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.PURPLE_ARMOR_OPTIC.get()).asItem());
            })
            .withTabsBefore(new ResourceLocation[]{CRUSTY_EXPLOSIVES.getId()})
            .build()
   );
   public static final DeferredHolder<CreativeModeTab, CreativeModeTab> WARIUM_ALUMINUM = REGISTRY.register(
      "warium_aluminum",
      () -> CreativeModeTab.builder()
            .title(Component.translatable("item_group.crusty_chunks.warium_aluminum"))
            .icon(() -> new ItemStack((ItemLike)CrustyChunksModBlocks.ALUMINUM_PLATING.get()))
            .displayItems((parameters, tabData) -> {
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_SLAB.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_STAIRS.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_TRAPDOOR.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_SIDE_PANEL.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_AC_BARREL.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_DARK_GRAY.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_SLAB_DARK_GRAY.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_STAIRS_DARK_GRAY.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_TRAPDOOR_DARK_GRAY.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_SIDE_PANEL_DARK_GRAY.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_AC_BARREL_DARK_GRAY.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_GREEN.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_SLAB_GREEN.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_STAIRS_GREEN.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_TRAPDOOR_GREEN.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_SIDE_PANEL_GREEN.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_AC_BARREL_GREEN.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_YELLOW.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_SLAB_YELLOW.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_STAIRS_YELLOW.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_TRAPDOOR_YELLOW.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_SIDE_PANEL_YELLOW.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_AC_BARREL_YELLOW.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_BROWN.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_SLAB_BROWN.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_STAIRS_BROWN.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_TRAPDOOR_BROWN.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_SIDE_PANEL_BROWN.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_AC_BARREL_BROWN.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_RED.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_SLAB_RED.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_STAIRS_RED.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_TRAPDOOR_RED.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_SIDE_PANEL_RED.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_AC_BARREL_RED.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_WHITE.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_SLAB_WHITE.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_STAIRS_WHITE.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_TRAPDOOR_WHITE.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_SIDE_PANEL_WHITE.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_AC_BARREL_WHITE.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_BLUE.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_SLAB_BLUE.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_STAIRS_BLUE.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_TRAPDOOR_BLUE.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_SIDE_PANEL_BLUE.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_AC_BARREL_BLUE.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_ORANGE.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_SLAB_ORANGE.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_STAIRS_ORANGE.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_TRAPDOOR_ORANGE.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_SIDE_PANEL_ORANGE.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_AC_BARREL_ORANGE.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_CYAN.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_SLAB_CYAN.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_STAIRS_CYAN.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_TRAPDOOR_CYAN.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_SIDE_PANEL_CYAN.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_AC_BARREL_CYAN.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_BLACK.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_SLAB_BLACK.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_STAIRS_BLACK.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_TRAPDOOR_BLACK.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_SIDE_PANEL_BLACK.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_AC_BARREL_BLACK.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_GRAY.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_SLAB_GRAY.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_STAIRS_GRAY.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_TRAPDOOR_GRAY.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_SIDE_PANEL_GRAY.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_AC_BARREL_GRAY.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_LIGHT_GRAY.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_SLAB_LIGHT_GRAY.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_STAIRS_LIGHT_GRAY.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_TRAPDOOR_LIGHT_GRAY.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_SIDE_PANEL_LIGHT_GRAY.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_AC_BARREL_LIGHT_GRAY.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_LIME.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_SLAB_LIME.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_STAIRS_LIME.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_TRAPDOOR_LIME.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_SIDE_PANEL_LIME.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_AC_BARREL_LIME.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_LIGHT_BLUE.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_SLAB_LIGHT_BLUE.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_STAIRS_LIGHT_BLUE.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_TRAPDOOR_LIGHT_BLUE.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_SIDE_PANEL_LIGHT_BLUE.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_AC_BARREL_LIGHT_BLUE.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_PINK.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_SLAB_PINK.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_STAIRS_PINK.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_TRAPDOOR_PINK.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_SIDE_PANEL_PINK.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_AC_BARREL_PINK.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_MAGENTA.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_SLAB_MAGENTA.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_STAIRS_MAGENTA.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_TRAPDOOR_MAGENTA.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_SIDE_PANEL_MAGENTA.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_AC_BARREL_MAGENTA.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_PURPLE.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_SLAB_PURPLE.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_STAIRS_PURPLE.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_TRAPDOOR_PURPLE.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_SIDE_PANEL_PURPLE.get()).asItem());
               tabData.accept(((Block)CrustyChunksModBlocks.ALUMINUM_AC_BARREL_PURPLE.get()).asItem());
            })
            .withTabsBefore(new ResourceLocation[]{WARIUM_ARMOR.getId()})
            .build()
   );

   @SubscribeEvent
   public static void buildTabContentsVanilla(BuildCreativeModeTabContentsEvent tabData) {
      if (tabData.getTabKey() == CreativeModeTabs.SPAWN_EGGS) {
         tabData.accept((ItemLike)CrustyChunksModItems.DECIMATOR_SPAWN_EGG.get());
         tabData.accept((ItemLike)CrustyChunksModItems.STRIKER_SPAWN_EGG.get());
         tabData.accept((ItemLike)CrustyChunksModItems.FLAMER_SPAWN_EGG.get());
         tabData.accept((ItemLike)CrustyChunksModItems.HUNTER_SPAWN_EGG.get());
         tabData.accept((ItemLike)CrustyChunksModItems.RIFLER_SPAWN_EGG.get());
         tabData.accept((ItemLike)CrustyChunksModItems.MORTARER_SPAWN_EGG.get());
         tabData.accept((ItemLike)CrustyChunksModItems.COMMANDER_SPAWN_EGG.get());
         tabData.accept((ItemLike)CrustyChunksModItems.CIWS_SPAWN_EGG.get());
         tabData.accept((ItemLike)CrustyChunksModItems.ASSASSIN_SPAWN_EGG.get());
         tabData.accept((ItemLike)CrustyChunksModItems.ERADICATOR_SPAWN_EGG.get());
         tabData.accept((ItemLike)CrustyChunksModItems.SCOUT_SPAWN_EGG.get());
         tabData.accept((ItemLike)CrustyChunksModItems.WORKER_SPAWN_EGG.get());
         tabData.accept((ItemLike)CrustyChunksModItems.REAPER_SPAWN_EGG.get());
         tabData.accept((ItemLike)CrustyChunksModItems.BREACHER_SPAWN_EGG.get());
         tabData.accept((ItemLike)CrustyChunksModItems.PROTOTYPE_ERADICATOR_SPAWN_EGG.get());
      }
   }
}
