package com.velocityspider.deathstar;

import org.slf4j.Logger;

import com.mojang.logging.LogUtils;
import com.velocityspider.deathstar.command.DeathStarCommand;
import com.velocityspider.deathstar.config.DeathStarConfig;
import com.velocityspider.deathstar.item.DeathStarCoreItem;

import net.minecraft.core.registries.Registries;
import net.minecraft.network.chat.Component;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.CreativeModeTabs;
import net.minecraft.world.item.Item;
import net.neoforged.bus.api.IEventBus;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.ModContainer;
import net.neoforged.fml.common.Mod;
import net.neoforged.fml.config.ModConfig;
import net.neoforged.neoforge.common.NeoForge;
import net.neoforged.neoforge.event.RegisterCommandsEvent;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.registries.DeferredItem;
import net.neoforged.neoforge.registries.DeferredRegister;

/**
 * Death Star Ruins.
 *
 * <p>Adds a scaled-down, battle-scarred Death Star that is summoned as a real physics body. The
 * shape is generated by {@link com.velocityspider.deathstar.structure.DeathStarBlueprint}, placed
 * into the world, and then assembled into a Sable physics sub-level by
 * {@link com.velocityspider.deathstar.structure.DeathStarAssembler} - so it tumbles, collides and
 * settles under the physics engine instead of just sitting there as placed blocks.
 */
@Mod(DeathStarMod.MODID)
public class DeathStarMod {

    public static final String MODID = "deathstar";
    public static final Logger LOGGER = LogUtils.getLogger();

    public static final DeferredRegister.Items ITEMS = DeferredRegister.createItems(MODID);
    public static final DeferredRegister<CreativeModeTab> CREATIVE_MODE_TABS =
            DeferredRegister.create(Registries.CREATIVE_MODE_TAB, MODID);

    /** The summon item: right-click the ground to drop a ruined Death Star there. */
    public static final DeferredItem<DeathStarCoreItem> DEATH_STAR_CORE = ITEMS.registerItem(
            "death_star_core", DeathStarCoreItem::new, new Item.Properties().stacksTo(16).fireResistant());

    public static final DeferredHolder<CreativeModeTab, CreativeModeTab> DEATH_STAR_TAB =
            CREATIVE_MODE_TABS.register("death_star_tab", () -> CreativeModeTab.builder()
                    .title(Component.translatable("itemGroup.deathstar"))
                    .withTabsBefore(CreativeModeTabs.COMBAT)
                    .icon(() -> DEATH_STAR_CORE.get().getDefaultInstance())
                    .displayItems((parameters, output) -> output.accept(DEATH_STAR_CORE.get()))
                    .build());

    public DeathStarMod(IEventBus modEventBus, ModContainer modContainer) {
        ITEMS.register(modEventBus);
        CREATIVE_MODE_TABS.register(modEventBus);

        // The command is a game (not mod-loading) event, so it goes on the NeoForge bus.
        NeoForge.EVENT_BUS.register(this);

        modContainer.registerConfig(ModConfig.Type.SERVER, DeathStarConfig.SPEC);
    }

    @SubscribeEvent
    public void onRegisterCommands(RegisterCommandsEvent event) {
        DeathStarCommand.register(event.getDispatcher());
    }
}
